// Mock Data - Metrics
import type { Metric } from '@/types'

export const mockMetrics: Metric[] = [
    // === REVENUE & FINANCE ===
    {
        id: 'metric-revenue',
        user_id: 'demo-user-1',
        name: 'Revenue',
        source: 'sales',
        aggregation: 'sum',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-profit',
        user_id: 'demo-user-1',
        name: 'Profit',
        source: 'finance',
        aggregation: 'sum',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-mrr',
        user_id: 'demo-user-1',
        name: 'Monthly Recurring Revenue (MRR)',
        source: 'saas',
        aggregation: 'sum',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-arr',
        user_id: 'demo-user-1',
        name: 'Annual Recurring Revenue (ARR)',
        source: 'saas',
        aggregation: 'sum',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-gross-margin',
        user_id: 'demo-user-1',
        name: 'Gross Margin',
        source: 'finance',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },

    // === CUSTOMER METRICS ===
    {
        id: 'metric-users',
        user_id: 'demo-user-1',
        name: 'Active Users',
        source: 'analytics',
        aggregation: 'count',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-customers',
        user_id: 'demo-user-1',
        name: 'Total Customers',
        source: 'crm',
        aggregation: 'count',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-new-customers',
        user_id: 'demo-user-1',
        name: 'New Customers',
        source: 'crm',
        aggregation: 'count',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-churn-rate',
        user_id: 'demo-user-1',
        name: 'Churn Rate',
        source: 'saas',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-retention-rate',
        user_id: 'demo-user-1',
        name: 'Retention Rate',
        source: 'saas',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-cac',
        user_id: 'demo-user-1',
        name: 'Customer Acquisition Cost (CAC)',
        source: 'marketing',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-ltv',
        user_id: 'demo-user-1',
        name: 'Customer Lifetime Value (LTV)',
        source: 'crm',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-nps',
        user_id: 'demo-user-1',
        name: 'Net Promoter Score (NPS)',
        source: 'survey',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },

    // === ECOMMERCE METRICS ===
    {
        id: 'metric-orders',
        user_id: 'demo-user-1',
        name: 'Total Orders',
        source: 'ecommerce',
        aggregation: 'count',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-aov',
        user_id: 'demo-user-1',
        name: 'Average Order Value (AOV)',
        source: 'ecommerce',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-cart-abandonment',
        user_id: 'demo-user-1',
        name: 'Cart Abandonment Rate',
        source: 'ecommerce',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-conversion',
        user_id: 'demo-user-1',
        name: 'Conversion Rate',
        source: 'analytics',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-items-sold',
        user_id: 'demo-user-1',
        name: 'Items Sold',
        source: 'ecommerce',
        aggregation: 'sum',
        created_at: '2024-01-10T10:00:00Z',
    },

    // === WEBSITE & TRAFFIC METRICS ===
    {
        id: 'metric-sessions',
        user_id: 'demo-user-1',
        name: 'Sessions',
        source: 'analytics',
        aggregation: 'sum',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-pageviews',
        user_id: 'demo-user-1',
        name: 'Page Views',
        source: 'analytics',
        aggregation: 'sum',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-bounce-rate',
        user_id: 'demo-user-1',
        name: 'Bounce Rate',
        source: 'analytics',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-avg-session-duration',
        user_id: 'demo-user-1',
        name: 'Average Session Duration',
        source: 'analytics',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-pages-per-session',
        user_id: 'demo-user-1',
        name: 'Pages Per Session',
        source: 'analytics',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-unique-visitors',
        user_id: 'demo-user-1',
        name: 'Unique Visitors',
        source: 'analytics',
        aggregation: 'count',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-returning-visitors',
        user_id: 'demo-user-1',
        name: 'Returning Visitors',
        source: 'analytics',
        aggregation: 'count',
        created_at: '2024-01-10T10:00:00Z',
    },

    // === MARKETING & ADS METRICS ===
    {
        id: 'metric-impressions',
        user_id: 'demo-user-1',
        name: 'Impressions',
        source: 'ads',
        aggregation: 'sum',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-clicks',
        user_id: 'demo-user-1',
        name: 'Clicks',
        source: 'ads',
        aggregation: 'sum',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-ctr',
        user_id: 'demo-user-1',
        name: 'Click-Through Rate (CTR)',
        source: 'ads',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-cpc',
        user_id: 'demo-user-1',
        name: 'Cost Per Click (CPC)',
        source: 'ads',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-cpm',
        user_id: 'demo-user-1',
        name: 'Cost Per Mille (CPM)',
        source: 'ads',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-ad-spend',
        user_id: 'demo-user-1',
        name: 'Ad Spend',
        source: 'ads',
        aggregation: 'sum',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-roas',
        user_id: 'demo-user-1',
        name: 'Return on Ad Spend (ROAS)',
        source: 'ads',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-leads',
        user_id: 'demo-user-1',
        name: 'Leads Generated',
        source: 'marketing',
        aggregation: 'count',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-lead-conversion',
        user_id: 'demo-user-1',
        name: 'Lead Conversion Rate',
        source: 'marketing',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },

    // === EMAIL & CONTENT METRICS ===
    {
        id: 'metric-email-opens',
        user_id: 'demo-user-1',
        name: 'Email Opens',
        source: 'email',
        aggregation: 'sum',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-email-open-rate',
        user_id: 'demo-user-1',
        name: 'Email Open Rate',
        source: 'email',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-email-ctr',
        user_id: 'demo-user-1',
        name: 'Email Click Rate',
        source: 'email',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-subscribers',
        user_id: 'demo-user-1',
        name: 'Email Subscribers',
        source: 'email',
        aggregation: 'count',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-unsubscribes',
        user_id: 'demo-user-1',
        name: 'Unsubscribes',
        source: 'email',
        aggregation: 'count',
        created_at: '2024-01-10T10:00:00Z',
    },

    // === SUPPORT & SERVICE METRICS ===
    {
        id: 'metric-tickets',
        user_id: 'demo-user-1',
        name: 'Support Tickets',
        source: 'support',
        aggregation: 'count',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-response-time',
        user_id: 'demo-user-1',
        name: 'Average Response Time',
        source: 'support',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-resolution-time',
        user_id: 'demo-user-1',
        name: 'Average Resolution Time',
        source: 'support',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
    {
        id: 'metric-csat',
        user_id: 'demo-user-1',
        name: 'Customer Satisfaction (CSAT)',
        source: 'support',
        aggregation: 'avg',
        created_at: '2024-01-10T10:00:00Z',
    },
]
