// Mock Data - Widgets
import type { Widget } from '@/types'

export const mockWidgets: Widget[] = [
    {
        id: 'widget-1',
        dashboard_id: 'dashboard-1',
        type: 'kpi',
        title: 'Total Revenue',
        metric_id: 'metric-revenue',
        config: {
            prefix: '$',
            color: '#0ea5e9',
        },
        position_x: 0,
        position_y: 0,
        width: 3,
        height: 2,
        created_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'widget-2',
        dashboard_id: 'dashboard-1',
        type: 'kpi',
        title: 'Active Users',
        metric_id: 'metric-users',
        config: {
            color: '#d946ef',
        },
        position_x: 3,
        position_y: 0,
        width: 3,
        height: 2,
        created_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'widget-3',
        dashboard_id: 'dashboard-1',
        type: 'kpi',
        title: 'Conversion Rate',
        metric_id: 'metric-conversion',
        config: {
            suffix: '%',
            color: '#10b981',
        },
        position_x: 6,
        position_y: 0,
        width: 3,
        height: 2,
        created_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'widget-4',
        dashboard_id: 'dashboard-1',
        type: 'line',
        title: 'Revenue Trend (30 Days)',
        metric_id: 'metric-revenue',
        config: {
            color: '#0ea5e9',
        },
        position_x: 0,
        position_y: 2,
        width: 6,
        height: 4,
        created_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'widget-5',
        dashboard_id: 'dashboard-1',
        type: 'bar',
        title: 'User Growth',
        metric_id: 'metric-users',
        config: {
            color: '#d946ef',
        },
        position_x: 6,
        position_y: 2,
        width: 6,
        height: 4,
        created_at: '2024-01-15T10:00:00Z',
    },
    {
        id: 'widget-6',
        dashboard_id: 'dashboard-1',
        type: 'pie',
        title: 'Traffic Sources',
        metric_id: 'metric-sessions',
        config: {
            showLegend: true,
        },
        position_x: 0,
        position_y: 6,
        width: 4,
        height: 3,
        created_at: '2024-01-15T10:00:00Z',
    },
]
